#!/usr/bin/env bash

image="/usr/share/backgrounds/${1}"
replace="/usr/share/backgrounds/${2}"

# Replace wallpaper.
if [[ -f "${image}" ]] && [[ -f "${replace}" ]]; then
    rm -rf "${image}"
    ln -s "${replace}" "${image}"
    chmod 644 "${replace}"
fi
