#!/usr/bin/env bash

image="/usr/share/backgrounds/xfce/xfce-${1}.png"
replace="/usr/share/backgrounds/${2}.png"

# Replace wallpaper.
if [[ -f "${image}" ]] && [[ -f "${replace}" ]]; then
    rm -rf "${image}"
    ln -s "${replace}" "${image}"
    chmod 644 "${replace}"
fi
